Repository thinkingmachines/geomancer, pull requests merged in 2019-03, with the labels that each got.

#13 Rename query_job return variable
  geomancer/spells/distance_to_nearest.py
Labels: bug

#18 Replace string templates with a query builder using SQLAlchemy
  Makefile
  geomancer/common/bqutils.py
  geomancer/spells/base.py
  geomancer/spells/distance_to_nearest.py
  requirements.in
  requirements.txt
Labels: enhancement

#37 Apply core.ST_GeoFromText to all geometries
  geomancer/spells/distance_to_nearest.py
  tests/backend/cores/test_bq.py
  tests/spells/base_test_spell.py
  tests/spells/test_distance_to_nearest.py
Labels: bug

#38 Apply filter to host before instantiating
  tests/spells/base_test_spell.py
  tests/spells/test_distance_to_nearest.py
Labels: bug, tests

#46 Refactor backend connection configuration to use database urls
  geomancer/backend/cores/base.py
  geomancer/backend/cores/bq.py
  geomancer/backend/cores/sqlite.py
  geomancer/spells/base.py
  tests/backend/cores/base_test_dbcore.py
  tests/backend/cores/test_bq.py
  tests/backend/cores/test_sqlite.py
  tests/spells/base_test_spell.py
  tests/spells/test_distance_to_nearest.py
  tests/spells/test_number_of.py
Labels: enhancement

#48 Add LengthOf
  geomancer/spells/__init__.py
  geomancer/spells/length_of.py
  tests/spells/test_length_of.py
Labels: documentation, enhancement, tests

#60 Remove white background in favicon
  docs/_static/favicon.ico
  docs/_static/logo.ico
  docs/conf.py
Labels: documentation
